### ISSUE TITLE
Can't quickly jump to marker "Al Basrah"

### ISSUE THREAD

**Issue by Ghost1005** [mahtoid/SquadMaps#35]
### Bug Description

headers_section  href = Albasrah error in lowercase B
id = AlBasrah please change section to Albasrah in uppercase B

**Comment by mahtoid** [comment]
Good spot! This has now been resolved, thank you. 💜

**Comment by Ghost1005** [comment]
> Good spot! This has now been resolved, thank you. 💜

Thank you for making these, which make the game more convenient for me, such as vehicle information, I only play vehicles in the game!
