### ISSUE TITLE
AlBasrah_Invasion_v8  and Mutaha_Seed_v1

### ISSUE THREAD

**Issue by Pepega1568** [mahtoid/SquadMaps#37]
### Bug Description

Fractions on AlBasrah_Invasion_v8 are specified incorrectly, Need to change to People's Liberation Army VS Insurgent Forces

https://docs.google.com/spreadsheets/d/1OYO1IvNI0wrUZWKz_pz6Ka1xFAvBjBupddYn2E4fNFg/edit#gid=84736544

And you need to add a Mutaha_Seed_v1 layer  https://imgur.com/a/rDWbTL7

United States Marine Corps VS Russian Ground Forces

**Comment by mahtoid** [comment]
Hey, thank you for letting me know!

I will update this roughly the same time the pipeline updates for the latest version (`4.4`).

💜

**Comment by mahtoid** [comment]
This has now been solved and updated. Let me know if you find anything else, thank you!

💜
