### ISSUE TITLE
[Feature] Sort by faction or type

### ISSUE THREAD

**Issue by jzju** [mahtoid/SquadMaps#38]
### Feature Description

Be able to filter on maps involving a certain faction or game mode.

**Comment by mahtoid** [comment]
Within the next version of the SquadMaps site there will be search functionality. This will allow you to search 'AAS', 'RAAS' etc and will narrow down your results to display just what is needed. 

Do you think this will give you exactly what you are asking for, or do you think there is more improvements which can be made there?

**Comment by mahtoid** [comment]
For example:

![image](https://user-images.githubusercontent.com/56257224/233851049-d75b51d6-a0c2-4cbe-8854-d3a62125fdc1.png)

**Comment by jzju** [comment]
It solves the typ e part but can you search for e.g. USMC to see only maps with them in it?

**Comment by mahtoid** [comment]
Ah, by layer factions as well. I'll have a think about how to implement that. I'll leave this ticket open while I think of a decent solution.

**Comment by mahtoid** [comment]
A solution may be to switch up the search to accept: `Faction Team Name` (singular), `Layer Name`, `Version Name` and `Map Name`

**Comment by mahtoid** [comment]
👀
![image](https://github.com/mahtoid/SquadMaps/assets/56257224/c613c22f-ccfa-4c4d-b327-9c49c619a688)

**Comment by D4n2021** [comment]
😱🤩 when will this be merged/be released to beta.squadmaps? 🤩

**Comment by mahtoid** [comment]
@D4n2021 Once we finish and clean up the styling for the map view page. Christmas has gotten in the way (how dare it), so it hasn't been completed quite yet.

**Comment by D4n2021** [comment]
Ok. Seems Christmas is the most programmer-hostile time of the year 😂

**Comment by mahtoid** [comment]
It's been a moment! This has now been released to [https://squadmaps.com](https://squadmaps.com).

Let me know if you think there is still more that can be solved around this.

💜
