### ISSUE TITLE
either remove the flags from the RAAS maps or add all possible flags to be displayed

### ISSUE THREAD

**Issue by D4n2021** [mahtoid/SquadMaps#39]
### Feature Description

Currently, when viewing an RAAS map (Anvil v1 for example https://squadmaps.com/img/maps/full_size/Anvil_RAAS_v1.jpg ), there are flags shown of a specific RAAS lane, instead of all possible RAAS flagzones. If possible it would be awesome to see all possible flagzones, if not, then better for them to be removed to not make all new players think that RAASv1 will _always_ be the same flags.

**Comment by mahtoid** [comment]
Hello @D4n2021,

I understand what you are saying here, on the the modal view - you will see (on the top right) redirection to Squadlanes which will allow people to learn and understand where the next flag point can be (along with an overview of all the flag points).

Currently this will remain unchanged on Squadmaps, however we have already improved this for Squadmaps v2 - which I'm sure you will be happy to hear.

---

I will close this issue out, but feel free to re-open if you can think of any other good ideas! 💜
