### ISSUE TITLE
[Feature] Adding the ability to link the specific layer view instead of just linking the map

### ISSUE THREAD

**Issue by BudMuecke** [mahtoid/SquadMaps#40]
### Feature Description

Hey,
currently Im developing a discord bot that displays gameserver information. To give players information about what vehicles a layer has, I provide a link to the squadmaps website. For example: https://squadmaps.com/#Yehorivka
The user then has to select the specific layer by himself and has to open the view to see the vehicles. 
I would love to be able to provide a direct link to the view where all vehicles are displayed. Is it possible in any way?
Thank you for your work by now!

**Comment by mahtoid** [comment]
This is a great suggestion and something which is supported within the next version already. 

I am still unsure on when this will be released as Tim (from Squadlanes) has gotten quite busy IRL and I am still awaiting the extractor changes to feed in the data.
